version: "3.3"

services:
  tg-subject:
    build: ../
    command: yarn run docker-test
    ports:
      - "8009:8009"
    depends_on:
      - tg-subject-rethinkdb
    networks:
      - restserve_ecosystem
    environment:
      - DB_HOST=tg-subject-rethinkdb
      - NODE_ENV=testing

  tg-subject-rethinkdb: 
    image: rethinkdb
    networks: 
      - restserve_ecosystem
       
networks: 
  restserve_ecosystem: 
    driver: bridge